version: "3.8"

services:
  web:
    environment:
      - TWITTER_API_TOKEN=${TWITTER_API_TOKEN}
    build: .
    ports:
      - "3000:3000"
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
