name: release-docker-image.yaml
on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - "api/**"
      - "cmd/**"
      - "internal/**"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
      - "./.github/workflows/release-docker-image.yaml"
    branches:
      - "!*"
      - "master"

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  BOT_USER_NAME: ${{ secrets.BOT_USER_NAME }}
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 12

    steps:
      - run: echo "🔥 The job triggered by a ${{ github.event_name }}"
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: build-docker-image.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
          persist-credentials: false

      - name: Setup Git
        run: |
          GIT_BRANCH=${{ github.ref }}
          echo "REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')" >> $GITHUB_ENV
          echo "GIT_BRANCH=$(echo "${GIT_BRANCH/refs\/heads\//}")" >> $GITHUB_ENV
          echo "COMMIT_DATE=$(git log -n 1 --pretty='format:%cd' --date=format:'%y-%m-%d')" >> $GITHUB_ENV
          echo "COMMIT_TIME=$(git log -n 1 --pretty='format:%cd' --date=format:'%H-%M-%S')" >> $GITHUB_ENV
          echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "GH_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          git config --global user.name "$BOT_USER_NAME"
          git config --global url."https://${{ env.GH_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{ env.GH_PAT }}:x-oauth-basic@github.com/".insteadOf "ssh://git@github.com/"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.BOT_USER_NAME }} # TODO: REPLACE THIS BY THE REAL BOT NAME
          password: ${{ secrets.DOCKER_PAT }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            mendesbarreto/${{ env.REPOSITORY_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=raw,value=${{ env.GIT_BRANCH }}-${{ env.COMMIT_DATE }}-${{ env.COMMIT_TIME }}-${{ env.GH_SHA_SHORT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        timeout-minutes: 15
        with:
          context: .
          network: host
          build-args: |
            GH_PAT=${{ secrets.GH_PAT }}
            BUILD_NR=${{ env.GIT_BRANCH }}-${{ env.GH_SHA_SHORT }}
            BUILD_BRANCH=${{ env.GIT_BRANCH }}
            BUILD_COMMIT=${{ env.GH_SHA_SHORT }}
            COMMIT_DATE=${{ env.COMMIT_DATE }}
            BUILD_DATE=${{ env.CURRENT_DATETIME }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
